"""ADD: maintenance_since to scooters

Revision ID: a2e9f10d65b8
Revises: f83cf1a0e5e0
Create Date: 2026-03-13 15:07:48.345841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e9f10d65b8'
down_revision = 'f83cf1a0e5e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scooters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('maintenance_since', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scooters', schema=None) as batch_op:
        batch_op.drop_column('maintenance_since')

    # ### end Alembic commands ###
