"""Add VehicleType, vehicle_type_uid to scooters and tariffs

Revision ID: d1ff2c63e714
Revises: a2e9f10d65b8
Create Date: 2026-03-16 10:28:26.328896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1ff2c63e714'
down_revision = 'a2e9f10d65b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_types',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('scooters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type_uid', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'vehicle_types', ['vehicle_type_uid'], ['uid'])

    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_type_uid', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'vehicle_types', ['vehicle_type_uid'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tariffs', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_type_uid')

    with op.batch_alter_table('scooters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicle_type_uid')

    op.drop_table('vehicle_types')
    # ### end Alembic commands ###
