"""initial schema

Revision ID: f83cf1a0e5e0
Revises: 
Create Date: 2026-03-13 11:16:32.415362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83cf1a0e5e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minute_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('users',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwort_hash', sa.String(length=255), nullable=False),
    sa.Column('user_rolle', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('payment_methods',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('rider_uid', sa.String(length=36), nullable=False),
    sa.Column('kartenidentifier_maskiert', sa.String(length=25), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rider_uid'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('scooters',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('uid_provider', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('qr_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gefahrene_km_gesamt', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('battery_level', sa.SmallInteger(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['uid_provider'], ['users.uid'], ),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_table('rides',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('rider_uid', sa.String(length=36), nullable=False),
    sa.Column('scooter_uid', sa.String(length=36), nullable=False),
    sa.Column('tarif_uid', sa.String(length=36), nullable=False),
    sa.Column('startzeit', sa.DateTime(), nullable=False),
    sa.Column('endzeit', sa.DateTime(), nullable=True),
    sa.Column('gesamtpreis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('gefahrene_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['rider_uid'], ['users.uid'], ),
    sa.ForeignKeyConstraint(['scooter_uid'], ['scooters.uid'], ),
    sa.ForeignKeyConstraint(['tarif_uid'], ['tariffs.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('transactions',
    sa.Column('uid', sa.String(length=36), nullable=False),
    sa.Column('ride_uid', sa.String(length=36), nullable=False),
    sa.Column('payment_method_uid', sa.String(length=36), nullable=False),
    sa.Column('betrag', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payment_method_uid'], ['payment_methods.uid'], ),
    sa.ForeignKeyConstraint(['ride_uid'], ['rides.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('rides')
    op.drop_table('scooters')
    op.drop_table('payment_methods')
    op.drop_table('users')
    op.drop_table('tariffs')
    # ### end Alembic commands ###
